name: PowerShell Pester Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Pester Tests
        shell: pwsh
        run: |
          $config = [PesterConfiguration]::Default
          $config.Run.Path = "./LazyWinAdminModule/Tests/*.Tests.ps1"
          $config.Run.Exit = $true
          $config.Output.Verbosity = 'Detailed'
          Invoke-Pester -Configuration $config
